#+title: Для себя

Дмитрий, здравствуйте.
Просмотрел тестовое внимательней. С ограничением времени ожидания ответа раньше не работал, планирую использовать long polling для этого. Остальное пока что вопросов не вызывает.
Вопросы:
- Как я могу получить доступ в тестовое окружение?
- Сроки. С учетом выходных, подходит ли крайний срок сдачи во вторник 12:00 (2022-09-27)? Естественно, если сделаю раньше, то скину раньше)

Что дальше:
-

* Использовать
=log.Println()=

* Запросы

#+name: body-1
#+begin_src json
  {}
#+end_src

#+name: test
#+begin_src shell :results output code :var body=body-1
  curl --request POST \
       --silent \
       -H 'Accept: application/json' \
       -H 'Content-Type: application/json' \
       -d body
       'http://localhost:5053/placements/request'
#+end_src

#+RESULTS: test
#+begin_src shell
#+end_src


#+begin_src emacs-lisp
  (use-package restclient)
#+end_src

#+name: Valid POST request
#+begin_src restclient :results output code
  POST http://127.0.0.1:5053/placements/request
  Content-Type: application/json


  {
    "id": "123",
    "tiles": [
      {
        "id": 123,
        "width": 122,
        "ratio": 1.5
      }
    ],
    "context": {
      "ip": "192.168.1.1",
      "user_agent": "curl"
    }
  }
#+end_src

#+RESULTS: Valid POST request
#+begin_src restclient
,#+BEGIN_SRC js
{
  "id": "123",
  "imp": [
    {
      "id": 123,
      "width": 155,
      "height": 133,
      "tile": "",
      "url": "upachka.com",
      "price": 143.5
    }
  ]
}
// POST http://127.0.0.1:5053/placements/request
// HTTP/1.1 200 OK
// Content-Type: application/json
// Date: Mon, 03 Oct 2022 13:37:07 GMT
// Content-Length: 100
// Request duration: 0.011154s
,#+END_SRC
#+end_src

#+RESULTS: valid req
#+begin_src restclient
,#+BEGIN_SRC js
{
  "id": "123",
  "imp": [
    {
      "id": 123,
      "width": 155,
      "height": 133,
      "tile": "",
      "url": "upachka.com",
      "price": 143.5
    }
  ]
}
// POST http://127.0.0.1:5053/placements/request
// HTTP/1.1 200 OK
// Content-Type: application/json
// Date: Mon, 26 Sep 2022 19:10:39 GMT
// Content-Length: 100
// Request duration: 0.015757s
,#+END_SRC
#+end_src

#+name: No id
#+begin_src restclient :results output code
  POST http://localhost:5053/placements/request
  Content-Type: application/json


  {
  "tiles": [{
  "id": 123,
  "width": 122,
  "ratio": 1.5
  }],
  "context": {
  "ip": "192.168.1.1",
  "user_agent": "curl"}
  }
#+end_src


#+name: Valid request, but GET instead POST
#+begin_src restclient :results output code
  POST http://127.0.0.1:5059/placements/request
#+end_src

* Что сделать
- [X] нет разбора строки с адресом:портом партнера.
- [X] кривой начальный запуск, пробовать запустить без waitgroup
- [X] асинхронно опрашивать партнеров.

* Тестовые ответы
#+begin_src js
  {
      "id": "123",
      "imp": [{
          "id": 123,
          "width": 144,
          "height": 122,
          "title": "Title1",
          "url": "example.com",
          "price": 123.5
      },{
          "id": 123,
          "width": 155,
          "height": 133,
          "title": "Title2",
          "url": "upachka.com",
          "price": 143.5
      }]
  }
#+end_src

* Дмитрию

Дмитрий, здравствуйте.
Ссылка на гит: https://git.foxyparadoxy.xyz/redmaycry/simple-choose-ad/

Насколько могу судить по мок серверу (написанному на коленке), работает. Было бы больше времени, порефакторил бы еще.

* правки 2022-10-03 пн
Дмитрий, здравствуйте

бэкенд "дсп" я написал, тестовое окружение - нет
вот сейчас потестировал руками
до конца дойти не получилось. передаю вам мои заметки по мотивам. поправите?

+ отмечены хорошие моменты, - плохие

+ не запускается без указания порта
- запускается с адресом dsp localhost:9001, но ругается что это неверный формат адреса
+/- отправка на стартовавший всё же сервер GET запроса на верный урл приводит к выводу текста WRONG_SCHEMA в лог
- но после этого сервер падает в панику
+ но не прекращает работу
+ последующий запрос POST (с пустым телом) тоже выводит WRONG_SCHEMA - то есть в целом сервер остался работоспособен
- но и паника на месте
+ отправка корректного запроса привела к коду 200, пустому телу ответа, и сообщению в логе, что нет ответов от дсп
- дсп запроса не получала
+ при запуске с адресом dsp 127.0.0.1:9001 запускается без ошибок
- запросы GET и POST с пустым телом по-прежнему вызывают панику
- корректный запрос отправляется в дсп, но в корень вместо /bid_request, поэтому тот отвечает кодом 404
- после чего мы видим в логе ошибку "invalid character 'p' after top-level value"
- попытка запуска с параметром -d "127.0.0.1:9001/bid_request" удалась
- но при попытке отправить запрос в логе возникает паника, что не удаётся сделать коннект к 127.0.0.1:0

* Правки
- [X] Проверка входящих значений ip:port, не допускать endpoint.
  - запускается с адресом dsp localhost:9001, но ругается что это неверный формат адреса
  - попытка запуска с параметром -d "127.0.0.1:9001/bid_request" удалась
  - но при попытке отправить запрос в логе возникает паника, что не удаётся сделать коннект к 127.0.0.1:0

- [X] Починить партнерский endpoint (сейчас запрос отправляется в корень).
  - корректный запрос отправляется в дсп, но в корень вместо /bid_request, поэтому тот отвечает кодом 404
  - после чего мы видим в логе ошибку "invalid character 'p' after top-level value"

+/- отправка на стартовавший всё же сервер GET запроса на верный урл приводит к выводу текста WRONG_SCHEMA в лог
- но после этого сервер падает в панику
+ но не прекращает работу
+ последующий запрос POST (с пустым телом) тоже выводит WRONG_SCHEMA - то есть в целом сервер остался работоспособен
- но и паника на месте
+ отправка корректного запроса привела к коду 200, пустому телу ответа, и сообщению в логе, что нет ответов от дсп
- дсп запроса не получала
- запросы GET и POST с пустым телом по-прежнему вызывают панику

* [2022-10-05 ср]

Вот что сделал:
+ неправильно парсил цену из json. Добавил `,string`
+ получил пустой тайл -- запаниковал. Теперь пропускаю.

DSP запустил, покрутил. Сделал bash скрипт с разными curl запросами, и есть такое ощущение, что на каждый tile DSP возвращает один imp (получается, что лучшую цену выбирать не из чего). Или, может быть, не разобрался с DSP до конца)

https://git.foxyparadoxy.xyz/redmaycry/simple-choose-ad

* 2022-10-18 вт
Есть два варианта.

1. Переписать отправку так, чтобы работала ас контекстом.
   https://www.alexedwards.net/blog/an-introduction-to-handlers-and-servemuxes-in-go
2.
